# Generated by Django 3.1.2 on 2020-10-28 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('producer', models.CharField(max_length=256)),
                ('info', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('image_preview', models.ImageField(upload_to='')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('per', 'Парфюм'), ('cos', 'Косметика')], max_length=3)),
                ('show', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_ends', models.DateField()),
                ('offer_image', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('dis', 'Скидка')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aroma', models.CharField(max_length=256)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=2)),
                ('order_address', models.CharField(max_length=512)),
                ('order_phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('order_status', models.CharField(choices=[('F', 'Получен'), ('C', 'Отменен'), ('P', 'Оплачен'), ('R', 'Зарезервирован'), ('O', 'Открыт')], max_length=1)),
                ('order_cost', models.FloatField()),
                ('date_reserved', models.DateField()),
                ('date_payed', models.DateField()),
                ('date_fulfilled', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goods')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialoffers')),
            ],
        ),
    ]
