# Generated by Django 3.1.2 on 2020-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201104_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='reference',
            field=models.CharField(default='offers/inactive', max_length=128),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(upload_to='goods/full'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image_preview',
            field=models.ImageField(upload_to='goods/previews'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='offer_image',
            field=models.ImageField(upload_to='specials/'),
        ),
    ]
