# Generated by Django 3.1.2 on 2020-10-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StockingGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_restocked', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goods')),
                ('restock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.stockinglog')),
            ],
        ),
    ]
