# Generated by Django 3.1.2 on 2020-11-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201104_0955'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockingGoods',
            new_name='StockingGood',
        ),
    ]
